### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [lfasmpao/Lyrica#1]
Hi, i love that your project is opensource. I am a graphic designer and i would love to contribute a logo to this project. It's free of course, that is if you'd like.

**Comment by lfasmpao** [comment]
Yeah sure. No problem 😊

**Comment by dee-y** [comment]
Hi there, here is a design i made... Was not sure if the color hits the mark so let me know if you have any color choices. I would also love to know in what sizes/types you would like me to export the logo? 

![lyrica-01](https://user-images.githubusercontent.com/36637989/44976580-88fe8100-af5d-11e8-8265-7ac6e201e019.jpg)

**Comment by lfasmpao** [comment]
Beautiful! You can send me the psd file :)

**Comment by dee-y** [comment]
Hello, i have created a PR here with requested files
https://github.com/lfasmpao/Lyrica/pull/2

cheers.
